// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/1/2025, 10:57:09 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/vincent/ixome/ixome-frontend/website-frontend/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/plugins/**/*.{js,ts,mjs}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/composables/**/*.{js,ts,mjs}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/utils/**/*.{js,ts,mjs}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/app.config.{js,ts,mjs}","/home/vincent/ixome/ixome-frontend/website-frontend/frontend/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})();

export default resolvedConfig;